django_template/urls.py
from django.conf import settings
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import path, include
from django.conf.urls.static import static
from django.views.static import serve
from django.conf.urls.i18n import i18n_patterns

from .settings import DEBUG

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/rosetta/', include('rosetta.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    url(r'^logout/$', LogoutView.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout')
]

urlpatterns += i18n_patterns(
    url(r'^', include('section.urls', namespace='section')),
    url(r'^', include('order.urls', namespace='order')),
    url(r'^', include('catalog.urls', namespace='catalog')),
    url(r'^feedback/', include('feedback.urls', namespace='feedback')),
    url(r'^', include('account.urls', namespace='account')),
    prefix_default_language=True
)

if DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
        url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    ]

feedback/urls.py
from django.urls import path
from .views import FeedbackView, SubscribeView

app_name = "feedback"

urlpatterns = [
    path('feedback/', FeedbackView.as_view(), name='feedback'),
    path('subs/', SubscribeView.as_view(), name='SubscribeView')
]

order/urls.py
from django.urls import path
from .views import CartView, OrderView
from django.views.decorators.csrf import csrf_exempt

app_name = "section"

urlpatterns = [
    path('order/', OrderView.as_view(), name='order'),
    path('order/confirm/', OrderView.confirm_order, name='confirm_order'),
    path('cart/', CartView.as_view(), name='cart'),
    path('cart/add/', CartView.add_item, name='add_item'),
    path('cart/delete/', csrf_exempt(CartView.delete_item), name='delete_item'),
    path('cart/edit/', csrf_exempt(CartView.edit_item), name='edit_item'),
]

section/urls.py
from django.urls import path
from .views import Index, NewsView, NewsDetailView, ContactView, LicenseView

app_name = "section"

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('contacts/', ContactView.as_view(), name='contacts'),
    path('license/', LicenseView.as_view(), name='license'),
    path('news/', NewsView.as_view(), name='news'),
    path('news/<slug:slug>/', NewsDetailView.as_view(), name='news_detail'),
]

templates/page/basket.html
{% extends 'base.html' %}
{% load static i18n %}
{% block title %}
    <title>Корзина</title>
{% endblock %}
{% block style %}
    {{ block.super }}
    <link type="text/css" href="{% static 'basket/basket.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}
    <!--                ******************************************* КОРЗИНА-->
    <div class="title">
        {% trans 'Корзина' %}
    </div>
    <div class="basket-products" id="ItemList">
        {% include "include/cart-item.html" with cart=cart %}
    </div>


    <div class="ordering-block">
        <div class="ordering-block-text">
            {% trans 'Сумма к оплате' %}:
        </div>
        <div class="ordering-block-prise" id="CartTotal">
            {{ cart.total }} ₽
        </div>
        <a href="{% url 'order:order' %}">
            <button type="submit" class="ordering-block-button">{% trans 'Оформить заказ' %}</button>
        </a>
        <a href="/#products" class="ordering-block-link">{% trans 'Вернуться к покупкам' %}</a>

    </div>

{% endblock %}
{% block scripts %}
{{ block.super }}
    <script src="{% static 'js/cart.js' %}"></script>
{% endblock %}

templates/page/certificate.html
{% extends 'base.html' %}
{% load static i18n %}
{% block title %}
    <title>Патенты и лицензии</title>
{% endblock %}
{% block style %}
    {{ block.super }}
    <link type="text/css" href="{% static 'certificate/certificate.css' %}" rel="stylesheet">
{% endblock %}
<!--                *******************************************  -->
{% block content %}
<div class="title">
    {% trans 'Патенты и лицензии' %}
</div>

<div class="certificates">
    {% for item in license %}
    <div class="certificate">
        <p class="certificate-title">
            {{ item.title }}
        </p>
        <img class="certificate-img" src="{{ item.image.url }}" alt="certificate">
    </div>
    {% endfor %}
</div>

{% endblock %}





{% block script %}
    {{ block.super }}
    <script src="{% static 'certificate/certificate.js' %}"></script>
{% endblock %}

templates/page/contacts.html
{% extends 'base.html' %}
{% load static i18n %}
{% block title %}
    <title>Контакты</title>
{% endblock %}
{% block style %}
    {{ block.super }}
    <link type="text/css" href="{% static 'contacts/contacts.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}
    <!--                *******************************************  -->
    <div class="title">
        {% trans 'Контакты' %}
    </div>

    <div class="contacts-block">
        <div class="contact">
            <img class="contact-img" src="{% static 'contacts/address.svg' %}" alt="address">
            <div class="contact-text">
                <div class="contact-title">
                    {% trans 'Адрес' %}
                </div>
                <div class="contact-info">
                    {{ cfg.address }}
                </div>
            </div>
        </div>
        <div class="contact">
            <img class="contact-img" src="{% static 'contacts/email.svg' %}" alt="address">
            <div class="contact-text">
                <div class="contact-title">
                    {% trans 'Электронная почта' %}
                </div>
                <div class="contact-info">
                    <a href="mailto:{{ cfg.email }}">
                        {{ cfg.email }}
                    </a>
                </div>
            </div>
        </div>
        <div class="contact">
            <img class="contact-img" src="{% static 'contacts/phone.svg' %}" alt="address">
            <div class="contact-text">
                <div class="contact-title">
                    {% trans 'Телефон' %}
                </div>
                <div class="contact-info">
                    <a href="tel:{{ cfg.phone }}">
                        {{ cfg.phone }}
                    </a>
                </div>
            </div>


        </div>
    </div>

    <iframe src="https://yandex.ru/map-widget/v1/?um=constructor%3Aefc1b954d0da9d13b87f6b8814beb3859b95620fe0c71083d24c03c4f092d17a&amp;source=constructor"
            width="100%" height="477" frameborder="0"></iframe>







{% endblock %}

templates/page/index.html
{% extends 'base.html' %}
{% load static i18n %}
{% block content %}
    <section id="catalog">
        <div class="title">
            {% trans 'Категории' %}
        </div>

        <div class="products">
            {% for category in categories %}
                {% if category_id %}
                <a class="product {% if category_id == category.id  %} active-product {% endif %}" href="?category={{ category.id }}#products">
                {% else %}
                <a class="product {% if first_category_id == category.id  %} active-product {% endif %}" href="?category={{ category.id }}#products">
                {% endif %}
                        <img class="product-img" src="{{ category.image.url }}" alt="t">
                        <p class="product-title">{{ category.title }}</p>
                </a>
            {% endfor %}
        </div>


        <!--    ******************************************* СПИСОК ТОВАРОВ-->
        <a name="products"></a>
        {% include 'include/product-include.html' with product_list=products count=products_count %}
    </section>


    <!-- ------------------------------------------Сертификаты -->
    {% if license %}
        <section id="cert">
            <div class="title">
                {% trans 'Патенты и лицензии' %}
            </div>

            <div class="certificates products-list">
                {% for item in license %}
                    <a href="{{ item.image.url }}" class=certificate-img">
                        <img src="{{ item.image.url }}" alt="{{ item.title }}"/>
                        <p class="certificate-text">{{ item.title }}</p>
                    </a>
                {% endfor %}
            </div>
            {% if license.paginator.num_pages > 1 %}
                <div class="scrollGoods">
                    <div class="scroll">
                        <div class="number-page">
                            <div class="this-page">
                                {{ license.number }}
                            </div>
                            <div class="all-page">
                                {% trans 'из' %} {{ license.paginator.num_pages }}
                            </div>
                        </div>
                        {% if license.has_previous %}
                            <a href="?licence_page={{ license.previous_page_number }}#cert" class="leftLink">
                                <img src="{% static 'product/scroll-left.svg' %}" alt="left">
                            </a>
                        {% endif %}
                        {% if license.has_next %}
                            <a href="?licence_page={{ license.next_page_number }}#cert" class="rightLink">
                                <img src="{% static 'product/scroll-right.svg' %}" alt="right">
                            </a>
                        {% endif %}
                    </div>
                </div>
            {% endif %}

        </section>
    {% endif %}

    <!-- ------------------------------------------NEWS -->
    {% if news %}
        <section id="news">
            <div class="title">
                {% trans 'Новости' %}
            </div>

            <div class="block-all-news">
                {% for item in news %}
                    <div class="block-news">
                        <a href="{% url 'section:news_detail' item.slug %}">
                        <img class="news-img" src="{{ item.image.url }}" alt="news"></a>

                        <div class="block-news-date">
                            <p>{{ item.date }}</p>
                        </div>
                        <a href="{% url 'section:news_detail' item.slug %}"
                           class="block-news-title">{{ item.title }}</a>
                    </div>
                {% endfor %}
            </div>
            {% if news.paginator.num_pages > 1 %}
                <div class="scrollGoods">
                    <div class="scroll">
                        <div class="number-page">
                            <div class="this-page">
                                {{ news.number }}
                            </div>
                            <div class="all-page">
                                {% trans 'из' %} {{ news.paginator.num_pages }}
                            </div>
                        </div>
                        {% if news.has_previous %}
                            <a href="?licence_page={{ news.previous_page_number }}#news" class="leftLink">
                                <img src="{% static 'product/scroll-left.svg' %}" alt="left">
                            </a>
                        {% endif %}
                        {% if news.has_next %}
                            <a href="?licence_page={{ news.next_page_number }}#news" class="rightLink">
                                <img src="{% static 'product/scroll-right.svg' %}" alt="right">
                            </a>
                        {% endif %}
                    </div>
                </div>
            {% endif %}
        </section>
    {% endif %}

    <!-- ********************************** Обратная связь-->
    <section id="feedback">
        <div class="title">
            {% trans 'Обратная связь' %}
        </div>

        <form id="regForm" action="{% url 'feedback:feedback' %}" enctype="multipart/form-data" method="post" class="reg-order-form">
            {% csrf_token %}
            <input type="text" name="name" placeholder="{% trans 'Имя' %} *" class="reg-form_name _req" required>

            <input type="text" name="surname" placeholder="{% trans 'Фамилия' %} *" class="reg-form_surname _req" required>

            <input type="tel" name="phone" id="reg-phone" placeholder="{% trans 'Телефон' %} *" class="reg-form_phone _req _tel"
                   required pattern="\+7\-[0-9]{3}\-[0-9]{3}\-[0-9]{2}\-[0-9]{2}">

            <input type="email" name="email" placeholder="{% trans 'Электронная почта' %} *" class="reg-form_email _req _email"
                   required>

            <textarea name="text" rows="1" id="comment" placeholder="{% trans 'Текст сообщения' %} *"
                      onkeypress="auto_grow(this)" onkeyup="auto_grow(this);" class="form_comment" required></textarea>

            <!--                    <textarea name="text"  class="f2" placeholder="Текст сообщения" required></textarea >-->


            <button id="reg-Button" class="reg-orderButton" type="submit">{% trans 'Отправить' %}</button>
        </form>

        <div class="modal-review" >
            <div class="modal-wrap-review">
                <p class="product-title">
                {% trans 'Спасибо за Ваш отзыв!' %}
                </p>

                <button class="close-modal-review" onclick="closeReviewModal()"><img class="close-modal-img-review"
                                                                     src="{% static 'product/modal-close.svg' %}"
                                                                     alt="close"></button>
            </div>

        </div>
    </section>


    <!-- ********************************** Контакты -->
    <section id="contacts">
        <div class="title">
            {% trans 'Контакты' %}
        </div>
        <div class="contacts-block">
            <div class="contact">
                <img class="contact-img" src="{% static 'contacts/address.svg' %}" alt="address">
                <div class="contact-text">
                    <div class="contact-title">
                        {% trans 'Адрес' %}
                    </div>
                    <div class="contact-info">
                        {{ cfg.address }}
                    </div>
                </div>
            </div>
            <div class="contact">
                <img class="contact-img" src="{% static 'contacts/email.svg' %}" alt="address">
                <div class="contact-text">
                    <div class="contact-title">
                        {% trans 'Электронная почта' %}
                    </div>
                    <div class="contact-info">
                        <a href="mailto:{{ cfg.email }}">
                            {{ cfg.email }}
                        </a>
                    </div>
                </div>
            </div>
            <div class="contact">
                <img class="contact-img" src="{% static 'contacts/phone.svg' %}" alt="address">
                <div class="contact-text">
                    <div class="contact-title">
                        {% trans 'Телефон' %}
                    </div>
                    <div class="contact-info">
                        <a href="tel:{{ cfg.phone }}">
                            {{ cfg.phone }}
                        </a>
                    </div>
                </div>


            </div>
        </div>

    <iframe src="https://yandex.ru/map-widget/v1/?um=constructor%3Aefc1b954d0da9d13b87f6b8814beb3859b95620fe0c71083d24c03c4f092d17a&amp;source=constructor" width="100%" height="477" frameborder="0"></iframe>

    </section>




    <div class="clear"></div>

    <a href="#feedback" class="site-feedback-link">
        {% trans 'Оставить о сайте' %}
    </a>
{% endblock %}
{% block scripts %}
    <script src="{% static 'js/comment.js' %}"></script>
    {{ block.super }}
{% endblock %}

templates/page/news.html
{% extends 'base.html' %}
{% load static i18n %}
{% block title %}<title>Новости</title>{% endblock %}
{% block style %}
    {{ block.super }}
    <link type="text/css" href="{% static 'news/news.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <!--                *******************************************  -->
    <div class="title">
        {% trans 'Новости' %}
    </div>

    <div class="block-all-news">
    {% for item in news %}
        <div class="block-news">
        {% if item.image %}
            <img class="news-img" src="{{ item.image.url }}" alt="news">
            {% endif %}
            <div class="block-news-date">
                <p>{{ item.date }}</p>
            </div>
            <a href="{% url 'section:news_detail' item.slug %}" class="block-news-title">{{ item.title }}</a>
        </div>

{% endfor %}
    </div>


    {% include 'include/pagination.html' with items=news %}
{% endblock %}

templates/page/one-news.html
{% extends 'base.html' %}
{% load static i18n %}


{% block title %} {{ news.title }} {% endblock %}
{% block style %}
    {{ block.super }}
    <link type="text/css" href="{% static 'one-news.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}
    <!--                *******************************************  -->

    <div class="news-bread-crumbs">
        <a href="/#news" class="news-bread-crumb-link">
            {% trans 'Назад' %}
        </a>
    </div>

    <div class="one-news">
        <div class="one-news-left">
            <div class="news-title">
                {{ news.title }}
            </div>
            <div class="one-news-date">
                <p>
                    {{ news.date }}
                </p>
            </div>
            <div class="new-text">
                <p>
                    {{ news.short_description }}
                </p>
            </div>
        </div>

        <div class="one-news-right">
            <img class="one-news-img" src="{{ news.image.url }}" alt="news-photo">
        </div>
    </div>

    <div class="new-text">
        {{ news.text|safe }}
    </div>

    <a href="/#news" class="all-news-link">
        {% trans 'Все новости' %}
    </a>

    <a href="/#feedback" class="site-feedback-link">
        {% trans 'Оставить о сайте' %}
    </a>





{% endblock %}

{% block scripts %}
    {{ block.super }}
{% endblock %}

templates/page/regist-order.html
{% extends 'base.html' %}
{% load static i18n %}

{% block style %}
    {{ block.super }}
    <link type="text/css" href="{% static 'regist-order/regist-order.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}
    <!--                *******************************************  ОФОРМЛЕНИЕ ЗАКАЗА-->
    <div class="title">
        {% trans 'Оформление заказа' %}
    </div>

    <div class="order-block">

        <p>{% trans 'Ваш заказ' %}:</p>

        <div class="order-block-products">
            {% for item in cart.cart_item.all %}
            <div class="order-block-product">
                <img class="order-block-photo" src="{{ item.product.image.url }}">
                <div class="order-block-text">
                    <div class="order-block-title">{{ item.product.title }}</div>
                    <div class="order-block-article">{{ item.product.article }}</div>
                </div>
                <p class="order-block-title">x{{ item.quantity }}</p>
                <p class="order-block-prise">{{ item.total }} ₽</p>
            </div>
            {% endfor %}
        </div>


        <div class="final-prise">
            <div>
                <p>{% trans 'Итого' %}:</p>
            </div>
            <div>
                <p>{{ cart.total }} ₽</p>
            </div>
        </div>

    </div>

    <div class="order-text">
        <p>
            {% trans 'Оставьте заявку и мы свяжемся с Вами в ближайшее время для подтверждения и оплаты заказа' %}
        </p>
    </div>
    <form id="form" action="{% url 'order:confirm_order' %}" enctype="multipart/form-data" method="post" class="order-form">
    {% csrf_token %}
        <input type="text" name="name" placeholder="{% trans 'Имя' %}" class="form_name _req" required>

        <input type="text" name="surname" placeholder="{% trans 'Фамилия' %}" class="form_surname _req" required>

        <input type="tel" name="phone" id="phone" placeholder="{% trans 'Телефон' %}" class="form_phone _req _tel"
               pattern="\+7\-[0-9]{3}\-[0-9]{3}\-[0-9]{2}\-[0-9]{2}" required>

        <input type="email" name="email" placeholder="{% trans 'Электронная почта' %}" class="form_email _req _email" required>

        <button class="orderButton" type="submit">{% trans 'Оформить заказ' %}</button>
    </form>

{% endblock %}

{% block script %}
    {{ block.super }}
    <script src="https://unpkg.com/imask"></script>
    <script>
        var element = document.getElementById('phone');
        var maskOptions = {
            mask: '+{7} (000) 000-00-00'
        };
        var mask = IMask(element, maskOptions);
    </script>

{#    <script src="{% static 'regist-order/validation-order-form.js' %}"></script>#}
    <script src="{% static 'js/order.js' %}"></script>
{% endblock %}