catalog/urls.py
from django.urls import path
from .views import ProductView

app_name = "section"

urlpatterns = [
    path('product/<int:pk>/', ProductView.as_view(), name='product')
]

django_template/urls.py
from django.conf import settings
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import path, include
from django.conf.urls.static import static
from django.views.static import serve
from django.conf.urls.i18n import i18n_patterns

from .settings import DEBUG

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/rosetta/', include('rosetta.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    url(r'^logout/$', LogoutView.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout')
]

urlpatterns += i18n_patterns(
    url(r'^', include('section.urls', namespace='section')),
    url(r'^', include('order.urls', namespace='order')),
    url(r'^', include('catalog.urls', namespace='catalog')),
    url(r'^feedback/', include('feedback.urls', namespace='feedback')),
    url(r'^', include('account.urls', namespace='account')),
    prefix_default_language=True
)

if DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
        url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    ]

order/urls.py
from django.urls import path
from .views import CartView, OrderView
from django.views.decorators.csrf import csrf_exempt

app_name = "section"

urlpatterns = [
    path('order/', OrderView.as_view(), name='order'),
    path('order/confirm/', OrderView.confirm_order, name='confirm_order'),
    path('cart/', CartView.as_view(), name='cart'),
    path('cart/add/', CartView.add_item, name='add_item'),
    path('cart/delete/', csrf_exempt(CartView.delete_item), name='delete_item'),
    path('cart/edit/', csrf_exempt(CartView.edit_item), name='edit_item'),
]

templates/include/cart-item.html
{% load static i18n %}

{% for item in cart.cart_item.all %}
    <div class="basket-product">
        <img class="basket-photo" src="{{ item.product.image.url }}">
        <div class="basket-text">
            <div class="basket-title">{{ item.product.title }}</div>
            <div class="basket-article">{{ item.product.article }}</div>
            <p class="basket-title del ButtonDelete" id="{{ item.id }}">{% trans 'Удалить из корзины' %}</p>
        </div>
        <div class="basket-count">
            <img src="{% static 'basket/minus.svg' %}" alt="minus" class="ButtonMinus" id="{{ item.id }}">
            <p class="basket-title">{{ item.quantity }}</p>
            <img src="{% static 'basket/plus.svg' %}" alt="plus" class="ButtonPlus" id="{{ item.id }}">
        </div>
        <div class="basket-prise">
            <p>{{ item.total }} {% trans '₽' %}</p>
        </div>
    </div>
{% endfor %}

templates/include/pagination.html
{% load static i18n %}
{{ category }}
{% if items.paginator.num_pages > 1 %}
    <div class="scrollGoods">
        <div class="scroll">
            <div class="number-page">
                <div class="this-page">
                    {{ items.number }}
                </div>
                <div class="all-page">
                    {% trans 'из' %} {{ items.paginator.num_pages }}
                </div>
            </div>
            {% if items.has_previous %}
                <a href="?page={{ items.previous_page_number }}{% if request.GET.category %}&category={{ request.GET.category }}{% endif %}{{ anchor }}" class="leftLink">
                    <img src="{% static 'product/scroll-left.svg' %}" alt="left">
                </a>
            {% endif %}
            {% if items.has_next %}
                <a href="?page={{ items.next_page_number }}{% if request.GET.category %}&category={{ request.GET.category }}{% endif %}{{ anchor }}" class="rightLink">
                    <img src="{% static 'product/scroll-right.svg' %}" alt="right">
                </a>
            {% endif %}
        </div>

    </div>
{% endif %}

templates/include/product-include.html
{% load static  i18n %}
<div class="title">
    {% trans 'Список товаров' %}
</div>
<div class="one-product-desc numb-products">
    {% trans 'Найдено' %} {{ count }} {% trans 'товаров' %}:
</div>
<div class="products-list">


    {% for product in product_list %}
        <a href="{% url 'catalog:product' product.id %}" class="one-product">
        <img class="one-product-img" src="{{ product.image.url }}" alt="product">
        <p class="one-product-art">{{ product.article }}</p>
        <p class="one-product-desc">{{ product.title }}
        </p>
        <div class="more">
            <p class="one-product-art">Подробнее</p>
            <img class="moreArrow" src="{% static 'arrowPodrobnee.svg' %}" alt="more">
        </div>
        </a>
    {% endfor %}
</div>

{% include 'include/pagination.html' with items=product_list anchor="#products" %}